apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neath-tan7026-pipejetui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/neath-tan7026-pipejetui.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: neath-tan7026-pipejetui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
